name: 'Submodule - Build'

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to build'
        required: false
        type: string
        default: '0.1.0'

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout project sources'
        uses: actions/checkout@v5

      - name: 'Setup Python 3.10'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 'Install build dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: 'Build package'
        run: make build
        env:
          VERSION: ${{ inputs.version }}

      - name: 'Check distribution'
        run: make check-dist

      - name: 'Upload build artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/
          retention-days: 30
