name: 'Submodule - Release'

on:
  workflow_call:
    inputs:
      level:
        required: true
        description: 'Version level to increase'
        type: string
        default: 'patch'
      pypi_repository:
        required: true
        description: 'Pypi repository URL'
        type: string
    secrets:
      pypi_username:
        required: true
        description: 'Pypi repository username'
      pypi_password:
        required: true
        description: 'Pypi repository password'

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Check out'
        uses: actions/checkout@v5

      - name: 'Get latest version'
        id: latest_version
        uses: starforge-universe/get-latest-version@v1
        with:
          default: 'v0.0.0'

      - name: 'Calculate next version'
        id: increased_version
        uses: starforge-universe/get-next-version@v1
        with:
          version: ${{ steps.latest_version.outputs.version }}
          level: ${{ inputs.level }}

      - name: 'Setup Python 3.10'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 'Install publishing infrastructure'
        run: pip install build twine

      - name: 'Build package'
        run: python3 -m build
        env:
          VERSION: ${{ steps.increased_version.outputs.version }}
          REQUIREMENTS: ${{ github.workspace }}/requirements.txt

      - name: 'Check distribution'
        run: twine check dist/*

      - name: 'Upload package'
        run: twine upload --repository-url ${{ inputs.pypi_repository }} -u ${{ secrets.pypi_username }} -p ${{ secrets.pypi_password }} dist/*

      - name: 'Tag with new version'
        id: tag-commit
        uses: issue-ops/semver@v2
        with:
          use-version: ${{ steps.increased_version.outputs.version }}
          overwrite: true
